sbatch exp_5_bash//BreakoutDeterministic-v4.sh 
sbatch exp_5_bash//AsterixDeterministic-v4.sh 
sbatch exp_5_bash//CarnivalDeterministic-v4.sh 
sbatch exp_5_bash//MsPacmanDeterministic-v4.sh 
sbatch exp_5_bash//UpNDownDeterministic-v4.sh 
sbatch exp_5_bash//AssaultDeterministic-v4.sh 
sbatch exp_5_bash//BerzerkDeterministic-v4.sh 
sbatch exp_5_bash//QbertDeterministic-v4.sh 
sbatch exp_5_bash//AmidarDeterministic-v4.sh 
sbatch exp_5_bash//SpaceInvadersDeterministic-v4.sh 
sbatch exp_5_bash//FrostbiteDeterministic-v4.sh 
sbatch exp_5_bash//KangarooDeterministic-v4.sh 
sbatch exp_5_bash//GravitarDeterministic-v4.sh 
sbatch exp_5_bash//TutankhamDeterministic-v4.sh 
sbatch exp_5_bash//RiverraidDeterministic-v4.sh 
