sbatch exp_2_bash//BreakoutDeterministic-v4.sh 
sbatch exp_2_bash//AsterixDeterministic-v4.sh 
sbatch exp_2_bash//CarnivalDeterministic-v4.sh 
sbatch exp_2_bash//MsPacmanDeterministic-v4.sh 
sbatch exp_2_bash//UpNDownDeterministic-v4.sh 
sbatch exp_2_bash//AssaultDeterministic-v4.sh 
sbatch exp_2_bash//BerzerkDeterministic-v4.sh 
sbatch exp_2_bash//QbertDeterministic-v4.sh 
sbatch exp_2_bash//AmidarDeterministic-v4.sh 
sbatch exp_2_bash//SpaceInvadersDeterministic-v4.sh 
sbatch exp_2_bash//FrostbiteDeterministic-v4.sh 
sbatch exp_2_bash//KangarooDeterministic-v4.sh 
sbatch exp_2_bash//GravitarDeterministic-v4.sh 
sbatch exp_2_bash//TutankhamDeterministic-v4.sh 
sbatch exp_2_bash//RiverraidDeterministic-v4.sh 
