sbatch exp_1_bash//BreakoutDeterministic-v4.sh 
sbatch exp_1_bash//AsterixDeterministic-v4.sh 
sbatch exp_1_bash//CarnivalDeterministic-v4.sh 
sbatch exp_1_bash//MsPacmanDeterministic-v4.sh 
sbatch exp_1_bash//UpNDownDeterministic-v4.sh 
sbatch exp_1_bash//AssaultDeterministic-v4.sh 
sbatch exp_1_bash//BerzerkDeterministic-v4.sh 
sbatch exp_1_bash//QbertDeterministic-v4.sh 
sbatch exp_1_bash//AmidarDeterministic-v4.sh 
sbatch exp_1_bash//SpaceInvadersDeterministic-v4.sh 
sbatch exp_1_bash//FrostbiteDeterministic-v4.sh 
sbatch exp_1_bash//KangarooDeterministic-v4.sh 
sbatch exp_1_bash//GravitarDeterministic-v4.sh 
sbatch exp_1_bash//TutankhamDeterministic-v4.sh 
sbatch exp_1_bash//RiverraidDeterministic-v4.sh 
