sbatch my_tes//BreakoutDeterministic-v4.sh 
sbatch my_tes//AsterixDeterministic-v4.sh 
sbatch my_tes//CarnivalDeterministic-v4.sh 
sbatch my_tes//MsPacmanDeterministic-v4.sh 
sbatch my_tes//UpNDownDeterministic-v4.sh 
sbatch my_tes//AssaultDeterministic-v4.sh 
sbatch my_tes//BerzerkDeterministic-v4.sh 
sbatch my_tes//QbertDeterministic-v4.sh 
sbatch my_tes//AmidarDeterministic-v4.sh 
sbatch my_tes//SpaceInvadersDeterministic-v4.sh 
sbatch my_tes//FrostbiteDeterministic-v4.sh 
sbatch my_tes//KangarooDeterministic-v4.sh 
sbatch my_tes//GravitarDeterministic-v4.sh 
sbatch my_tes//TutankhamDeterministic-v4.sh 
sbatch my_tes//RiverraidDeterministic-v4.sh 
