sbatch DOrig_bash//BreakoutDeterministic-v4.sh 
sbatch DOrig_bash//AsterixDeterministic-v4.sh 
sbatch DOrig_bash//CarnivalDeterministic-v4.sh 
sbatch DOrig_bash//MsPacmanDeterministic-v4.sh 
sbatch DOrig_bash//UpNDownDeterministic-v4.sh 
sbatch DOrig_bash//AssaultDeterministic-v4.sh 
sbatch DOrig_bash//BerzerkDeterministic-v4.sh 
sbatch DOrig_bash//QbertDeterministic-v4.sh 
sbatch DOrig_bash//AmidarDeterministic-v4.sh 
sbatch DOrig_bash//SpaceInvadersDeterministic-v4.sh 
sbatch DOrig_bash//FrostbiteDeterministic-v4.sh 
sbatch DOrig_bash//KangarooDeterministic-v4.sh 
sbatch DOrig_bash//GravitarDeterministic-v4.sh 
sbatch DOrig_bash//RiverraidDeterministic-v4.sh 
