sbatch exp_50_bash//BreakoutDeterministic-v4.sh 
sbatch exp_50_bash//AsterixDeterministic-v4.sh 
sbatch exp_50_bash//CarnivalDeterministic-v4.sh 
sbatch exp_50_bash//MsPacmanDeterministic-v4.sh 
sbatch exp_50_bash//UpNDownDeterministic-v4.sh 
sbatch exp_50_bash//AssaultDeterministic-v4.sh 
sbatch exp_50_bash//BerzerkDeterministic-v4.sh 
sbatch exp_50_bash//QbertDeterministic-v4.sh 
sbatch exp_50_bash//AmidarDeterministic-v4.sh 
sbatch exp_50_bash//SpaceInvadersDeterministic-v4.sh 
sbatch exp_50_bash//FrostbiteDeterministic-v4.sh 
sbatch exp_50_bash//KangarooDeterministic-v4.sh 
sbatch exp_50_bash//GravitarDeterministic-v4.sh 
sbatch exp_50_bash//RiverraidDeterministic-v4.sh 
