sbatch ex100_bash//BreakoutDeterministic-v4.sh 
sbatch ex100_bash//AsterixDeterministic-v4.sh 
sbatch ex100_bash//CarnivalDeterministic-v4.sh 
sbatch ex100_bash//MsPacmanDeterministic-v4.sh 
sbatch ex100_bash//UpNDownDeterministic-v4.sh 
sbatch ex100_bash//AssaultDeterministic-v4.sh 
sbatch ex100_bash//BerzerkDeterministic-v4.sh 
sbatch ex100_bash//QbertDeterministic-v4.sh 
sbatch ex100_bash//AmidarDeterministic-v4.sh 
sbatch ex100_bash//SpaceInvadersDeterministic-v4.sh 
sbatch ex100_bash//FrostbiteDeterministic-v4.sh 
sbatch ex100_bash//KangarooDeterministic-v4.sh 
sbatch ex100_bash//GravitarDeterministic-v4.sh 
sbatch ex100_bash//RiverraidDeterministic-v4.sh 
