sbatch l65_p1_bash//BreakoutDeterministic-v4.sh 
sbatch l65_p1_bash//AsterixDeterministic-v4.sh 
sbatch l65_p1_bash//CarnivalDeterministic-v4.sh 
sbatch l65_p1_bash//UpNDownDeterministic-v4.sh 
sbatch l65_p1_bash//AssaultDeterministic-v4.sh 
sbatch l65_p1_bash//BerzerkDeterministic-v4.sh 
sbatch l65_p1_bash//QbertDeterministic-v4.sh 
sbatch l65_p1_bash//AmidarDeterministic-v4.sh 
sbatch l65_p1_bash//SpaceInvadersDeterministic-v4.sh 
sbatch l65_p1_bash//FrostbiteDeterministic-v4.sh 
sbatch l65_p1_bash//KangarooDeterministic-v4.sh 
sbatch l65_p1_bash//GravitarDeterministic-v4.sh 
sbatch l65_p1_bash//RiverraidDeterministic-v4.sh 
sbatch l65_p1_bash//HeroDeterministic-v4.sh 
sbatch l65_p1_bash//JamesbondDeterministic-v4.sh 
sbatch l65_p1_bash//SeaquestDeterministic-v4.sh 
sbatch l65_p1_bash//BankHeistDeterministic-v4.sh 
sbatch l65_p1_bash//AirRaidDeterministic-v4.sh 
sbatch l65_p1_bash//SolarisDeterministic-v4.sh 
sbatch l65_p1_bash//WizardOfWorDeterministic-v4.sh 
sbatch l65_p1_bash//ZaxxonDeterministic-v4.sh 
sbatch l65_p1_bash//FreewayDeterministic-v4.sh 
sbatch l65_p1_bash//VentureDeterministic-v4.sh 
sbatch l65_p1_bash//RoadRunnerDeterministic-v4.sh 
sbatch l65_p1_bash//TutankhamDeterministic-v4.sh 
sbatch l65_p1_bash//KungFuMasterDeterministic-v4.sh 
sbatch l65_p1_bash//KrullDeterministic-v4.sh 
sbatch l65_p1_bash//CentipedeDeterministic-v4.sh 
sbatch l65_p1_bash//MsPacmanDeterministic-v4.sh 
sbatch l65_p1_bash//AlienDeterministic-v4.sh 
