sbatch new_bash//BreakoutDeterministic-v4.sh 
sbatch new_bash//AsterixDeterministic-v4.sh 
sbatch new_bash//CarnivalDeterministic-v4.sh 
sbatch new_bash//UpNDownDeterministic-v4.sh 
sbatch new_bash//AssaultDeterministic-v4.sh 
sbatch new_bash//BerzerkDeterministic-v4.sh 
sbatch new_bash//QbertDeterministic-v4.sh 
sbatch new_bash//AmidarDeterministic-v4.sh 
sbatch new_bash//SpaceInvadersDeterministic-v4.sh 
sbatch new_bash//FrostbiteDeterministic-v4.sh 
sbatch new_bash//KangarooDeterministic-v4.sh 
sbatch new_bash//GravitarDeterministic-v4.sh 
sbatch new_bash//RiverraidDeterministic-v4.sh 
sbatch new_bash//HeroDeterministic-v4.sh 
sbatch new_bash//JamesbondDeterministic-v4.sh 
sbatch new_bash//SeaquestDeterministic-v4.sh 
sbatch new_bash//BankHeistDeterministic-v4.sh 
sbatch new_bash//AirRaidDeterministic-v4.sh 
sbatch new_bash//SolarisDeterministic-v4.sh 
sbatch new_bash//WizardOfWorDeterministic-v4.sh 
sbatch new_bash//ZaxxonDeterministic-v4.sh 
sbatch new_bash//FreewayDeterministic-v4.sh 
sbatch new_bash//VentureDeterministic-v4.sh 
sbatch new_bash//RoadRunnerDeterministic-v4.sh 
sbatch new_bash//TutankhamDeterministic-v4.sh 
sbatch new_bash//KungFuMasterDeterministic-v4.sh 
sbatch new_bash//KrullDeterministic-v4.sh 
sbatch new_bash//CentipedeDeterministic-v4.sh 
sbatch new_bash//MsPacmanDeterministic-v4.sh 
sbatch new_bash//AlienDeterministic-v4.sh 
