sbatch exp_10_bash//BreakoutDeterministic-v4.sh 
sbatch exp_10_bash//AsterixDeterministic-v4.sh 
sbatch exp_10_bash//CarnivalDeterministic-v4.sh 
sbatch exp_10_bash//MsPacmanDeterministic-v4.sh 
sbatch exp_10_bash//UpNDownDeterministic-v4.sh 
sbatch exp_10_bash//AssaultDeterministic-v4.sh 
sbatch exp_10_bash//BerzerkDeterministic-v4.sh 
sbatch exp_10_bash//QbertDeterministic-v4.sh 
sbatch exp_10_bash//AmidarDeterministic-v4.sh 
sbatch exp_10_bash//SpaceInvadersDeterministic-v4.sh 
sbatch exp_10_bash//FrostbiteDeterministic-v4.sh 
sbatch exp_10_bash//KangarooDeterministic-v4.sh 
sbatch exp_10_bash//GravitarDeterministic-v4.sh 
sbatch exp_10_bash//TutankhamDeterministic-v4.sh 
sbatch exp_10_bash//RiverraidDeterministic-v4.sh 
